name: Test compile SIIDJ java 5

env:
  JAVA_TOOL_OPTIONS: -Dfile.encoding=iso-8859-1 -Xms256m -Xmx800m -XX:MaxPermSize=200m -Djava.net.preferIPv4Stack=true -Duser.timezone=America/Bogota -Xms512m -Xmx768m -Xss256k -XX:MaxPermSize=256M -XX:+ShowMessageBoxOnError
  ANT_OPTS: -Dfile.encoding=iso-8859-1 
  JAVA_HOME: /usr/lib/jvm/java5/jdk1.5.0_12
on: workflow_dispatch

permissions:
  id-token: write
  contents: read    # This is required for actions/checkout

jobs:
  deployQA:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          clean: false  # This is required to keep the build files

      - name: Uninstall Java 11
        run: | 
          sudo apt remove temurin* -y

      - name: Install Java 5
        run: | 
          echo Running install java 5
          echo Started on `date`
          #sudo apt-get update
          #sudo apt-get install sun-java5-jdk
          sudo mkdir /usr/lib/jvm/java5
          sudo cp builds/build/jdk-1_5_0_12-linux-amd64.bin /usr/lib/jvm/java5/jdk-1_5_0_12-linux-amd64.bin
          sudo chmod a+x /usr/lib/jvm/java5/jdk-1_5_0_12-linux-amd64.bin
          sudo chown -R root:root /usr/lib/jvm/java5/
          cd /usr/lib/jvm/java5/
          sudo echo "yes" | sudo ./jdk-1_5_0_12-linux-amd64.bin

          sudo update-alternatives --install "/usr/bin/java" "java" "/usr/lib/jvm/java5/jdk1.5.0_12/bin/java" 1
          sudo update-alternatives --install "/usr/bin/javac" "javac" "/usr/lib/jvm/java5/jdk1.5.0_12/bin/javac" 1
          #sudo update-alternatives --install "/usr/bin/javaws" "javaws" "/usr/lib/jvm/java5/jdk1.5.0_12/bin/javaws" 1

          sudo update-alternatives --set java /usr/lib/jvm/java5/jdk1.5.0_12/bin/java
          sudo update-alternatives --set javac /usr/lib/jvm/java5/jdk1.5.0_12/bin/javac

          sudo chmod a+x /usr/bin/java
          sudo chmod a+x /usr/bin/javac
          #sudo chmod a+x /usr/bin/javaws

          sudo chown -R root:root /usr/lib/jvm/java5/
          echo $JAVA_HOME
          export JAVA_HOME=/usr/lib/jvm/java5/jdk1.5.0_12
          echo $JAVA_HOME
          echo $PATH
          export PATH=$JAVA_HOME/bin:$PATH
          echo "PATH changed"
          echo $PATH
          echo "java version"
          java -version
          #echo "javac version"
          #javac -version
          echo Done on `date`
        
      - name: Install Ant
        run: | # Install Ant, specifict version that supports Java 5
          sudo apt remove ant -y
          sudo mkdir /opt/ant
          sudo tar -xvf builds/build/apache-ant-1.7.1-bin.tar.gz -C /opt/ant
          sudo update-alternatives --install "/usr/bin/ant" "ant" "/opt/ant/apache-ant-1.7.1/bin/ant" 1
          sudo update-alternatives --set ant /opt/ant/apache-ant-1.7.1/bin/ant
          export ANT_HOME=/opt/ant/apache-ant-1.7.1
          echo $PATH
          export PATH=$ANT_HOME/bin:$PATH
          echo "PATH changed"
          echo $PATH
         # sudo ant -v

         # sudo apt install snapd
         # sudo snap install ant --channel=1.9/stable --classic
         # echo "java version"
         # java -version

      - name: Compile with ant
        run: | 
          echo Running pre_build
          cd /usr/lib/jvm/
          echo Lo que hay en la ruta
          ls
          echo Lo que hay en la segunda ruta
          ls /usr/lib/jvm/
          sudo rm -r java-1.11.0-openjdk-amd64
          sudo rm -r java-11-openjdk-amd64
          cat default-java

