name: Compile java 5 Windows

#env:
  #JAVA_TOOL_OPTIONS: -Dfile.encoding=iso-8859-1 -Xms256m -Xmx800m -XX:MaxPermSize=200m -Djava.net.preferIPv4Stack=true -Duser.timezone=America/Bogota -Xms512m -Xmx768m -Xss256k -XX:MaxPermSize=256M -XX:+ShowMessageBoxOnError
  #ANT_OPTS: -Dfile.encoding=iso-8859-1 
  #JAVA_HOME: /usr/lib/jvm/java5/jdk1.5.0_12


on: workflow_dispatch

permissions:
  id-token: write
  contents: read    # This is required for actions/checkout

jobs:
  deployQA:
    name: Deploy
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          clean: false  # This is required to keep the build files

      - name: Install Java 5
        run: | 
          dir
          D:\a\githubPrueba\githubPrueba\jdk-1_5_0_21-windows-i586-p.exe
      - name: Verify environments variables
        run: set
